Milestone 1. with Pairprogramming in School-library project on refectoring-codebase Branch
PowerLevel9000/School-library pull request #6
Opened 2023-04-24 15:19 UTC by otmanTR

In this branch following changes done:
-ui_creater.rb file created
-UiCreater class created
-Created title_ui function
-Created table_ui function
-Created ui_creater function
-Changed hard code and used these functions and code become more DRY

2023-04-24 16:08 UTC, Gambit142 requested changes
Hi @otmanTR @PowerLevel9000 👋, 

Good job so far!

## Highlights
- All linters checks passed ✔️ 
- App class is in a new file ✔️ 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:

N/A

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please, remember to tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-04-24 16:08 UTC, Gambit142 commented on app.rb
>      print 'Enter the option : '
- [ ] It would be nice to put all codes that request inputs or validate input in a separate method. They shouldn't be in the methods that create `Person`, `Book` or `Rental` instances. 👍 🌵 Kindly do this for all the methods that create an instance in the App class. 💻

2023-04-24 16:29 UTC, PowerLevel9000 commented on app.rb
>      print 'Enter the option : '
# Thanks for Review 🙏🙏🙏

hi @Gambit142  thanks for diving deep into our code base 

- [ ] For person instances it looks great to refactor those instances as a separate method but for other things which ultimately create one line console print it actually create an extra line to create one line please guide us with your expertise 🧑‍💻🧑‍💻💪💪💪💕

2023-04-24 17:52 UTC, Ismailco approved these changes
### Hi @otmanTR, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![cr-approve](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)


## Highlights

✔️ No linter errors
✔️ Used Gitflow
✔️ Work documented professionally

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-24 18:48 UTC, Gambit142 commented on app.rb
>      print 'Enter the option : '
Hi @PowerLevel9000, we can meet up to look at the code base and work on it. 👍

2023-04-25 01:36 UTC, PowerLevel9000 commented
# Thank you 💪💪💪🙏🙏🙏

![ThankYouSoMuchPrabhasGIF](https://user-images.githubusercontent.com/116451144/233258767-f3943ca4-fbe2-4fde-b8b1-2129593266e5.gif)


Hello @Ismailco @Gambit142 ,

I wanted to express my gratitude for your willingness to take the time to review my code on GitHub. Your feedback and suggestions have been instrumental in improving the quality of my work, and I appreciate your insights and expertise in this area.

It's inspiring to have someone like you, who is knowledgeable and experienced, provide valuable feedback that helps me enhance my coding skills. I truly appreciate the time and effort you put into reviewing my code, and I'm grateful for your constructive criticism.

If there are any areas that I need to work on, please don't hesitate to let me know. I'm open to hearing any suggestions or recommendations you may have. Your feedback is essential to my growth as a developer, and I value it tremendously.

Thank you again for your time and for sharing your expertise with me. I'm looking forward to applying the insights gained from your review to my future projects.

Sincerely,
@PowerLevel9000

2023-04-25 01:38 UTC, PowerLevel9000 commented on app.rb
>      print 'Enter the option : '
hi @Gambit142  sure
💕💕💕

2023-04-25 01:38 UTC, merged